#!/usr/bin/env bash
# Beta-function wing → mesh pipeline:
#   1. run beta_function_wing → output/innerboundary.dat
#   2. parse kleft/kright → generate params.inc
#   3. build mesh
set -e
cd "$(dirname "$0")/.."
mkdir -p output

NPROC=${NPROC:-8}

# ---- run beta (use beta_params.txt if present, else interactive) ----
echo "=== beta-function wing ==="
./build/beta_function_wing 2>&1 | tee build/beta_output.log

# ---- parse kleft, kright ----
KLEFT=$(grep -oP 'kleft=\s*\K[0-9]+' build/beta_output.log | tail -1)
KRIGHT=$(grep -oP 'kright=\s*\K[0-9]+' build/beta_output.log | tail -1)

if [[ -z "$KLEFT" || -z "$KRIGHT" ]]; then
    echo "Error: failed to parse kleft/kright from output" >&2
    exit 1
fi
echo "kleft=$KLEFT  kright=$KRIGHT"

# ---- generate params.inc ----
IMAX=${IMAX:-41};    JMAX=${JMAX:-41};    KMAX=${KMAX:-91}
IARC=${IARC:-5};     SPAN=${SPAN:-4.0};   DOMAIN=${DOMAIN:-40.0}
RAD=${RAD:-30.0};    NUM_ITER=${NUM_ITER:-100}; NUM_INNER=${NUM_INNER:-300}
OMEGA=${OMEGA:-1.30}; SIGMA=${SIGMA:-0.02}

cat > params.inc << EOF
! params.inc — auto-generated by beta.sh
      parameter (imax=${IMAX},jmax=${JMAX},kmax=${KMAX})               ! grid dimensions
      parameter (kleft=${KLEFT},kright=${KRIGHT},iarc=${IARC})          ! wing K-range & arc points
      parameter (span_length=${SPAN}d0,domain_length=${DOMAIN}d0)        ! span & domain extent
      parameter (rad=${RAD}d0)                                           ! O-mesh section radius
      parameter (num_iter=${NUM_ITER})                                    ! outer iterations
      parameter (num_inner=${NUM_INNER})                                  ! inner iterations (NMAX)
      parameter (omega=${OMEGA}d0,sigma=${SIGMA}d0)                      ! relaxation & smoothing
EOF

cat params.inc

# ---- build mesh ----
make mesh

echo "=== Done. Run: mpirun -np $NPROC ./build/mesh ==="
