#!/usr/bin/env bash
# Generate params.inc from command-line arguments or defaults.
# Usage: gen_params.sh [imax jmax kmax kleft kright iarc span domain rad num_iter num_inner omega sigma]
set -e

IMAX=${1:-41};       JMAX=${2:-41};       KMAX=${3:-91}
KLEFT=${4:-24};      KRIGHT=${5:-68};     IARC=${6:-5}
SPAN=${7:-4.0};      DOMAIN=${8:-40.0}
RAD=${9:-30.0}
NUM_ITER=${10:-100}; NUM_INNER=${11:-300}
OMEGA=${12:-1.30};   SIGMA=${13:-0.02}

cat > params.inc << EOF
! params.inc — auto-generated by gen_params.sh
      parameter (imax=${IMAX},jmax=${JMAX},kmax=${KMAX})               ! grid dimensions
      parameter (kleft=${KLEFT},kright=${KRIGHT},iarc=${IARC})          ! wing K-range & arc points
      parameter (span_length=${SPAN}d0,domain_length=${DOMAIN}d0)        ! span & domain extent
      parameter (rad=${RAD}d0)                                           ! O-mesh section radius
      parameter (num_iter=${NUM_ITER})                                    ! outer iteration count
      parameter (num_inner=${NUM_INNER})                                  ! inner iteration count (NMAX)
      parameter (omega=${OMEGA}d0,sigma=${SIGMA}d0)                      ! relaxation & smoothing
EOF

echo "Wrote params.inc:"
cat params.inc
